# Causal Inference {.tabset}

Much of social science is about causality.  We might ask questions like whether [voter registration increases political participation](https://egap.org/resource/electoral-administration-in-kenya/), whether [bottom-up accountability can improve health outcomes](https://egap.org/resource/does-bottom-up-accountability-work-evidence-from-uganda/), or whether [personal narratives of immigrants help reduce prejudicial attitudes towards them](https://egap.org/resource/brief-70-how-personal-narratives-reduce-negative-attitudes-towards-immigrants-in-kenya/).

Gran parte del estudio de las ciencias sociales está centrado alrededor de la causalidad. Nos hacemos preguntas del tipo: [¿aumenta la participación política el registro de votantes?] (https://egap.org/resource/electoral-administration-in-kenya/),  [¿pueden los sistemas de rendición de cuentas que vayan de abajo hacia arriba mejorar los resultados (outcomes?) de salud?] (https: // egap.org/resource/does-bottom-up-accountability-work-evidence-from-uganda/), o [¿ayudan las narrativas personales de los inmigrantes  a reducir las actitudes perjudiciales hacia ellos?] (https://egap.org/resource/brief -70-cómo-las-narrativas-personales-reducen-las-actitudes-negativas-hacia-los-inmigrantes-en-Kenia /).

A lo largo de la última década, el campo de las ciencias sociales se ha vuelto mucho más riguroso al momento de hacer afirmaciones de tipo causal, basándose en una larga historia de trabajo sobre causalidad que se remonta a los escritos clásicos de [Fisher y Rubin] (# causalinference-classics). El uso de experimentos se ha vuelto cada vez más común y la aleatorización se ha convertido en una regla de oro para abordar temas de causalidad.


En este módulo presentamos el enfoque contrafactual de la inferencia causal y cómo se pueden interpretar las declaraciones con afirmaciones de tipo causal. Presentamos el marco de salidas potenciales  y cómo la asignación aleatoria nos ayuda a hacer afirmaciones sobre lo que habría sucedido en ausencia de alguna política pública, acción o programa que estudiamos. También discutimos los tres supuestos básicos necesarios para la inferencia causal: asignación aleatoria de sujetos a tratamientos, no interferencia y excluibilidad.




## Contenido Principal

 - ¿A qué nos referimos cuando decimos que algo es una **causa** de algo más? ¿Y por qué es importante ser claro acerca de lo que una afirmación de tipo causal quiere decir?

- Una introducción al tema de **salidas potenciales** como forma para pensar en alternativas para posibles estados del mundo.

 - La **aleatorización** nos ayuda a entender las afirmaciones contrafactuales de tipo causal de una forma particularmente útil.
 
 
- Los tres **supuestos básicos** claves para la inferencia causal: asignación aleatoria de sujetos al tratamiento, no interferencia y posibilidad de exclusión.

 - Comparación de estudios aleatorizados con estudios observacionales.

 - La aleatorización contibruye significativamente a la validez interna, pero no promete **validez externa**.

 - Una pregunta causal está estrechamente relacionada con el [diseño de investigación](the-research-design-process.html).
 
 



 
## Diapositivas

A continuación presentamos las diapositivas con el contenido principal cubierto durante nuestra clase sobre causalidad. Usted puede usar directamente los archivos originales de las diapositivas o también puede copiarlos y editarlos localmente.

- [Archivo de R Markdown](https://egap.github.io/learningdays-resources/Slides/causalinference-slides.Rmd)

- [Versión en PDF](https://egap.github.io/learningdays-resources/Slides/causalinference-slides.pdf)

- [Version de HTML](https://egap.github.io/learningdays-resources/Slides/causalinference-slides.html)

Si desea, también puede ver las diapositivas utilizadas en sesiones previas de los Learning Days de EGAP:

 - [Presentación sobre inferencia causal de los Learning Days de EGAP en la Escuela Africana de Economía, Abomey-Calavi, Junio de 2019](https://egap.github.io/learningdays-resources/Slides/Examples/causality-benin.pdf)

 - [Presentación sobre inferencia causal de los Learning Days de EGAP en la Universidad de Los Andes, Bogotá, Abril de 2019](https://egap.github.io/learningdays-resources/Slides/Examples/causality-bogota.pdf)

 - [Presentación sobre inferencia causal de los Learning Days de EGAP en la Universidad Católica del Uruguay, Montevideo, Marzo de 2018](https://egap.github.io/learningdays-resources/Slides/Examples/causality-montevideo.pdf)

 - [Presentación sobre inferencia causal de los Learning Days de EGAP en  la Ciudad de Guatemala, Guatemala, Agosto 2017](https://egap.github.io/learningdays-resources/Slides/Examples/causality-guatemala.pdf)

 - [Presentación de la clase de Introducción a Experimentos de los Learning Days de EGAP en la Ciudad de Guatemala, Guatemala, Agosto de 2017](https://egap.github.io/learningdays-resources/Slides/Examples/intro_experiments-guatemala.pdf)

 - [Presentación sobre inferencia causal de los Learning Days de EGAP en Salima, Malawi, Febrero 2017](https://egap.github.io/learningdays-resources/Slides/Examples/causality-malawi.pdf)

 - [Presentación sobre inferencia causal de los Learning Days de EGAP  en la Universidad Diego Portales in Santiago, Chile, Mayo de 2016](https://egap.github.io/learningdays-resources/Slides/Examples/causality-santiago.pdf)

## Recursos

### Guías de Métodos de EGAP (en Inglés)

- Guía de Métodos de EGAP [10 Things You Need to Know about Causal Inference](https://egap.org/resource/10-things-to-know-about-causal-inference/)

- Guía de Métodos de EGAP [10 Strategies for Figuring Out If X Caused Y](https://egap.org/resource/10-strategies-figuring-out-if-x-caused-y/)

- Guía de Métodos de EGAP [10 Things You Need to Know about Mechanisms](https://egap.org/resource/10-things-mechanisms/)

- Guía de Métodos de EGAP [10 Things to Know About External Validity](https://egap.org/resource/10-things-to-know-about-external-validity/)

### Libros, Capítulos y Artículos {#causalinference-cites}


#### Clásicos {#causalinference-classics}

- [@fisher_design_1935]. Fisher presenta la idea de aleatorización y pruebas de hipótesis como forma de entender a la inferencia causal.

- [@rubin:1974]. Rubin presenta el concepto de salidas potenciales y conecta el cocepto de causalidad a la inferencia estadística.

#### Trabajos Contemporáneos (Contemporary Overviews)

- [@brady2008causation].

- [@gerber_field_2012, Capítulo 1]. Este libro es un gran recurso para muchos temas sobre diseño experimental.

- [@morgan_counterfactuals_2007, Chapter 1].  Este libro contiene ejemplos de cómo pensar la formulación de afirmaciones causales partiendo de datos obsevacionales.

- [@glennerster_running_2013]. Este libro es una gran introducción a cómo realizar experimentos de campo donde también se discuten muchos ejemplos prácticos.

### Notas de EGAP sobre políticas:

Algunos ejemplos de preguntas causales:

- [ Nota 38 de EGAP sobre políticas: ¿Son efectivas las campañas educativas radiales para disuadir a los votantes de votar por partidos y candidatos que compren votos?](https://egap.org/resource/brief-38-diminishing-the-effectiveness-of-vote-buying-through-voter-education/)

- [Nota 51 de EGAP sobre políticas:  ¿pueden los sistemas de rendición de cuentas que van de abajo a arriba mejorar los resultados en materia de salud?](https://egap.org/resource/does-information-technology-improve-public-service-delivery-lessons-from-uganda/)


- [Nota 69 de EGAP sobre políticas: ¿Sirven los sistemas enfocados en el ciudadano y que van de abajo a arriba para ayudar a mejorar la prestación de servicios públicos?](https://egap.org/resource/brief-69-bottom-up-accountability-and-public-service-provision-in-brazil/)


