# Estimandos y Estimadores {.tabset}

Los experimentos aleatorios nos permiten hacer inferencias correctas sobre el promedio de una variable de interés bajo tratamiento y bajo control. Esto nos permite definir estimadores insesgados de los efectos promedio del tratamiento. También podemos usar la aleatorización para describir cómo las estimaciones generadas por un estimador pueden variar de un experimento a otro en forma de errores estándar e intervalos de confianza.

En este módulo presentamos varios tipos de estimandos, es decir, la cantidad objetivo que queremos estimar. La elección de la estimación es una decisión científica y basada en políticas: ¿qué estimando nos ayuda a tomar esta decisión? Además, como parte del diseño de la investigación, debemos seleccionar un estimador apropiado para esta cantidad. A continuación, discutimos cómo utilizar los estimadores con nuestros datos para generar estimaciones de nuestro estimando y cómo caracterizar la variabilidad de esta estimación.

## Contenido Principal

- Un **efecto causal**, $\tau_i$, es una comparación de cantidades potenciales no observadas para cada unidad $i$.  Esta puede ser, por ejemplo, una diferencia o un radio de cantidades potenciales no observadas.

- Para obtener más información sobre $\tau_i$, podemos tratar $\tau_{i}$ como un **estimando** o cantidad objetivo a estimar (este módulo) o como una cantidad objetivo sobre la que se puede formular hipótesis ([ módulo de pruebas de hipótesis] (hypothesis-testing.html)).

- Es común utilizar el **Efecto promedio del tratamiento (average treatment effect, ATE)**, $\bar{\tau} = \sum_ {i = 1}^n \tau_{i}$, en parte, porque permite una **estimación** fácil.

- Un **estimador** es una receta para estimar el valor de un estimando. Por ejemplo, la diferencia entre la media de resultados observados para $m$ unidades tratadas y la media de resultados observados para $N-m$ unidades no tratadas es un estimador de $\bar {\tau}$.

- Cada iteración de una aleatorización producirá diferentes valores del mismo estimador que busca estimar el mismo estimando. El **error estándar** resume esta variabilidad en un estimador.

- Un **intervalo de confianza** de $100 (1- \alpha)$%  es una colección de hipótesis que no se pueden rechazar en el nivel $\alpha$. Tendemos a informar intervalos de confianza que contienen hipótesis sobre los valores de nuestro estimador y usamos nuestro estimador como una estadística de prueba.

- Los estimadores deben 1) evitar errores sistemáticos al estimar el estimando (no sesgar); 2) varíar poco en sus inferencias de un experimento a otro (ser preciso o eficiente); y quizás idealmente 3) converger al estimando a medida que usan más y más información (ser consistente).

 - **Analizar mientras se aleatoriza** en el contexto de la estimación significa que 1) nuestros errores estándar deben medir la variabilidad de la aleatorización y 2) nuestros estimadores deben apuntar a estimaciones definidas en términos de resultados potenciales.

 - No **controlamos** covariables de fondo cuando analizamos datos de experimentos aleatorios. Pero las covariables pueden hacer que nuestra estimación sea más **precisa**. Esto se denomina **ajuste de covarianza**. El ajuste de covarianza en experimentos aleatorios no es lo mismo que el control de variables en estudios observacionales.

 - Una intervención de políticas (como por ejemplo un volante fomentando el ejercicio) puede *tener la intención* de cambiar el comportamiento a través de una **dosis activa** (ejercicio real). Podemos aprender sobre el efecto causal de la intención asignando la entrega de volantes al azar; esta es el  **efecto de la intención de tratar** (intent to treat effect, **ITT**). .
 
 - Podemos aprender sobre el efecto causal del ejercicio real mediante el uso de la asignación aleatoria de cartas como **instrumento** para la dosis activa (el ejercicio en sí) con el fin de conocer el efecto causal del ejercicio **entre aquellos que cambiarían su comportamiento después de recibir la carta**. Las versiones de efecto causal promedio de estos efectos a menudo se conocen como **efecto causal promedio del cumplidor** o **efecto de tratamiento promedio local**.
 
## Diapositivas


A continuación presentamos las diapositivas con el contenido principal que cubrimos en nuestra clase sobre estimación.



- [Archivo de R Markdown](https://egap.github.io/learningdays-resources/Slides/estimation-slides.Rmd)

- [Versión en PDF](https://egap.github.io/learningdays-resources/Slides/estimation-slides.pdf)

- [Versión de HTML](https://egap.github.io/learningdays-resources/Slides/estimation-slides.html)

Si desea, también puede ver las diapositivas utilizadas en sesiones previas de los Learning Days de EGAP:

 - [Presentación sobre Estimación de Los Learning Days de EGAP Learning en La Escuela Africana de Economía, Abomey-Calavi, Junio de 2019](https://egap.github.io/learningdays-resources/Slides/Examples/estimation-benin.pdf)

 - [Presentación sobre Estimación de Los Learning Days de EGAP Learning en la Universidad de Los Andes, Bogotá, April 2019](https://egap.github.io/learningdays-resources/Slides/Examples/estimation-bogota.pdf)

 - [Presentación sobre Estimación de Los Learning Days de EGAP Learning en la Universidad Católica del Uruguay, Montevideo, March 2018](https://egap.github.io/learningdays-resources/Slides/Examples/estimation-montevideo.pdf)

 - [Presentación sobre Estimación de Los Learning Days de EGAP Learning en la Universidad Diego Portales in Santiago, Chile, May 2016](https://egap.github.io/learningdays-resources/Slides/Examples/estimation-santiago.pdf)

También puede ver la discusión de los problemas de estimar el efecto de la dosis activa de un tratamiento en estas diapositivas (así como la discusión de los problemas que causan los datos faltantes sobre los resultados para la estimación de los efectos causales promedio):

- [The design issues presentation from EGAP Learning Days at the African School of Economics, Abomey-Calavi, June 2019 (first section reviews randomization designs)](https://egap.github.io/learningdays-resources/Slides/Examples/threats-benin.pdf)

- [Presentación sobre propagación y deserción de los Learning Days de EGAP en la Ciudad de Guatemala City, Guatemala, Agosto de  2017](https://egap.github.io/learningdays-resources/Slides/Examples/spillovers_attrition-guatemala.pdf)

- [Presentación sobre las complicaciones en Los Learning Days de EGAP en la Ciudad de Guatemala, Guatemala, Agosto 2017](https://egap.github.io/learningdays-resources/Slides/Examples/threats-guatemala.pdf)

- [Presentación sobre las complicaciones en Los Learning Days de EGAP en Salima, Malawi, Febrero de 2017](https://egap.github.io/learningdays-resources/Slides/Examples/complications-malawi.pdf)

- [Presentación sobre amenazas  en la Universidad Diego Portales in Santiago, Chile, Mayo de 2016 (la sección de la mitad trata sobre ITT e incumplimiento )](https://egap.github.io/learningdays-resources/Slides/Examples/threats-santiago.pdf)


## Resources

### Guías de Métodos de EGAP

 -  Guía de Métodos de EGAP
 [10 Tipos de Efectos de Tratamiento que usted debe conocer](https://egap.org/resource/10-types-of-treatment-effect-you-should-know-about/)

 - Guía de Métodos de EGAP [10 cosas que usted debe saber sobre ajuste de covarianza](https://egap.org/resource/10-things-to-know-about-covariate-adjustment/)

 - Guía de Métodos de EGAP [10 cosas que usted debe saber sobre datos faltantes](https://egap.org/resource/10-things-to-know-about-missing-data/)

 - Guía de Métodos de EGAP [10 Cosas que debe saber sobre effectos de propagación sobre Efectos locales promedio de tratamiento](https://egap.org/resource/10-things-to-know-about-the-local-average-treatment-effect/)

 - Guía de Métodos de EGAP [10 Cosas que debe saber sobre effectos de propagación (Spillover)](https://egap.org/resource/10-things-to-know-about-spillovers/)

### Books, Chapters, and Articles

 - [@gerber_field_2012]. Capítulo 2.7 sobre excluibilidad y no interferencia, Capítulo 3, Capítulo 5 sobre incumplimiento unilateral, Capítulo 6 sobre incumplimiento bilateral, Capítulo 7 sobre desgaste, Capítulo 8 sobre interferencia entre unidades experimentales.

 - [@bowers2020causality].


###  Herramientas

- [DeclareDesign](https://declaredesign.org)

- [estimatr: Paquete de R](https://declaredesign.org/r/estimatr/)

