# Otros temas {.tabset}



A continuación referenciamos enlaces a recursos que sirven para aprender sobre temas que no se pueden cubrir en profundidad durante el taller pero que aun así son importantes para el diseño experimental

## Contenido Principal
 
- Flujo de trabajo
  - La memoria humana es limitada; necesitamos reglas y herramientas que nos permitan recordar y compartir
  - Para que lo que hagamos sea reproducible necesitamos código y procesos de archivaos eficientes y claros.

- Validez Externa
  - Gran parte de este libro trata el tema de la validez externa. 
  - Esto no implica que se pueda extrapolar a otras poblaciones. 
  - ¿Qué concesiones debemos que hacer? ¿Cómo se puede extrapolar?

- Inferencia de aleatorización y procedimientos en ri2
  - La inferencia de aleatorización (randomization inference) es un método para calcular valores p para pruebas de hipótesis.
  - ri2 es un paquete de R que  permite correr simulaciones para calcular p valores usando  inferencia de aleatorización para distintos estimandos.
  
- Entendiendo los resultados
  - Cómo enteder e interpretar la salida de una regresión? 
  
- Integrando la investigación cualitativa

- Diseños Adaptativos
  - La mayoría de los diseños son estáticos: es decir, se aplican los mismos procedimientos para asignar tratamientos y medir los resultados durante todo el ensayo.
 - Los diseños adaptables ajustan el tratamiento de la asignación y la asignación de control en función del análisis intermedio del resultado del ensayo.

- Meta análisis

## Diapositivas

## Recursos

### Métodos Guías de EGAP

- [10 Things to Know About Project Workflow](https://egap.org/resource/10-things-to-know-about-project-workflow/)
- [10 Things to Know About Randomization Inference](https://egap.org/resource/10-things-to-know-about-randomization-inference/)
- [10 Things to Know About Missing Data](https://egap.org/resource/10-things-to-know-about-missing-data/)

### Libros, Capítulos y Artículos

 - [¿Cómo mejorar la relación con tu yo futuro?] (https://github.com/jwbowers/workflow)
 - [La Iniciativa de Berkeley para la Transparencia en las Ciencias Sociales] (https://www.bitss.org/)
 

