# Randomization {.tabset}

En el módulo de [inferencia causal] (causal-inference.html) discutimos el crucial rol que tiene la aleatorización al momento de hacer inferencias válidas para comparar grupos tratados y no tratados. En este módulo, pasamos de la teoría a la primera de muchas opciones concretas para el diseño de la investigación.



A continuación presentamos cuatro formas comunes de aleatorizar el tratamiento: simple, completo, en bloque y conglomerados. Así mismo discutimos cuándo cada uno de estos tipos de aleatorización pueden ser usadados. Además presentamos varios diseños populares, incluidos diseños factoriales y diseños de estímulos. El módulo proporciona algunas pautas sobre la implementación, incluyendo las mejores prácticas para verificar el equilibrio y garantizar la replicabilidad.

## Contenido Principal

- ¿Qué es la **aleatorización**? La asignación aleatoria a tratamientos **no** es lo mismo que el muestreo aleatorio.

- Cuatro formas comunes para aleatorizar un tratamiento:

    - ** Simple **: asigna unidades al azar al tratamiento (como un lanzamiento de moneda).

    - ** Completa **: dentro de una lista de unidades elegibles, se asigna un número fijo que va a recibir el tratamiento (como una urna).

    - ** Bloque (o estratificado) **: se asignan unidades dentro de estratos o bloques específicos al tratamiento, como si estuviera ejecutando un experimento dentro de cada bloque.
      
    - ** Conglomerados **: asigna grupos (conglomerados) de observaciones a la misma condición de tratamiento.
    
- Algunos diseños populares:
    
    - ** Acceso ** aleatorizado: se aleatoriza si el tratamiento va a estar disponible.
    
    - Aleatorizado ** acceso retardado **: aleatoriza el momento en el que el tratamiento va a estar disponible.
    
    - ** Factorial **: aleatorizar unidades a combinaciones de (brazos) tratamientos.
    
    - ** Estímulo **: aleatorizar la invitación para recibir tratamiento.

- ¿Cómo saber si la aleatorización produjo grupos homogeneos con respecto a las características observables? Para verificar esto, por lo general se realizan pruebas de aleatorización, también conocidas como pruebas de homogeneidad entre grupos. Se puede, por ejemplo, utilizar la prueba ómnibus $d^2 $ de `xBalance` del el paquete` RItools` (porque es una inferencia de aleatorización) o podemos aproximar este resultado con una prueba de $F$.

- A continuación discutimos sólo algunos de **los limites que naturalmente tiene la aleatorización**. En el módulo sobre [amenazas](threats-to-internal-validity-of-randomized-experiments.html) encontrará más información al respecto.

##  Diapositivas

A continuación presentamos las diapositivas con el contenido principal que cubrimos en nuestra clase sobre aleatorización.  Usted puede usar directamente los archivos originales de las diapositivas o también puede copiarlos y editarlos localmente.

- [Archivos de R Markdown](https://egap.github.io/learningdays-resources/Slides/randomization-slides.Rmd)

- [Versión en PDF](https://egap.github.io/learningdays-resources/Slides/randomization-slides.pdf)

- [Version de HTML](https://egap.github.io/learningdays-resources/Slides/randomization-slides.html)

Los archivos vinculados muestran cómo [hacer aleatorización replicable en R] (https://egap.github.io/learningdays-resources/Exercises/randomization-exercises.Rmd). También puede ver más ejemplos de aleatorización en R en [10 cosas que necesita saber sobre la aleatorización] (https://egap.org/resource/10-things-to-know-about-randomization/).

Si desea, también puede ver las diapositivas utilizadas en sesiones previas de los Learning Days de EGAP:

- [Presentación sobre los problemas del diseño en los Learning Days de EGAP en la Escuela Africana de Economía, Abomey-Calavi, junio de 2019 (la primera sección explora diseños de aleatorización)](https://egap.github.io/learningdays-resources/Slides/Examples/threats-benin.pdf)

- [Presentación sobre aleatarización en los Learning Days de EGAP en Universidad de Los Andes, Bogotá, Abril de 2019](https://egap.github.io/learningdays-resources/Slides/Examples/randomization-bogota.pdf)

- [Presentación sobre aleatarización en los Learning Days de EGAP en la Universidad Católica del Uruguay, Montevideo, Marzo de 2018](https://egap.github.io/learningdays-resources/Slides/Examples/randomization-montevideo.pdf)

- [Presentación sobre aleatarización en los Learning Days de EGAP en la Ciudad de Guatemala Guatemala, Agosto de  2017](https://egap.github.io/learningdays-resources/Slides/Examples/randomization-guatemala.pdf)

- [Presentación sobre aleatarización en los Learning Days de EGAP en Salima, Malawi, Febrero de 2017](https://egap.github.io/learningdays-resources/Slides/Examples/randomization-malawi.pdf)

- [Presentación sobre aleatarización en los Learning Days de EGAP en la  Universidad Diego Portales in Santiago, Chile, Mayo de 2016](https://egap.github.io/learningdays-resources/Slides/Examples/randomization-santiago.pdf)


## Recursos 

### Guías de Métodos de EGAP

- Guías de Métodos de EGAP [Las 10 cosas que usted debe saber sobre aleatorización](https://egap.org/resource/10-things-to-know-about-randomization/)

- EGAP Methods Guide [Las 10 cosas que usted debe saber sobre aleatorización por aglomerados](https://egap.org/resource/10-things-to-know-about-cluster-randomization/)

### Libros, Capítulos y Artículos

- [Procedimiento operativo estándar para el laboratioria de Don Green en la Universidad de Columbia](https://github.com/acoppock/Green-Lab-SOP). Un extenso conjunto de procedimientos  y reglas generales para llevar a cabo estudios experimentales.

- [@glennerster_running_2013]. El capítulo 2 trata temas de aleatorización 

- [@gerber_field_2012]. Capítulo 2: Inferencia causal y aleatorización

### Informe de Políticas de EGAP

*Diseños Factoriales*

- [Informe de Políticas de EGAP 57 : Cómo los medios de comunicación cambian las normas: Evidencia de México](https://egap.org/resource/how-media-influence-social-norms-evidence-from-mexico/)

- [Informe de Políticas de EGAP  58: Funciona la rendición de cuentas que parten desde la base?](https://egap.org/resource/does-bottom-up-accountability-work-evidence-from-uganda/)

*Randomizing access*

- [Informe de Políticas de EGAP 24: Reduciendo la "captura por la elite" en las islas Salomon](https://egap.org/resource/brief-24-reducing-elite-capture-in-the-solomon-islands/)

*Aleatorizando el acceso retardado*

  - [Informe de Políticas de EGAP 35: Reduciendo la reinicidencia  entre exconvictos](https://egap.org/resource/brief-35-reducing-reconvictions-among-released-prisoners/)

  - [Informe de Políticas de EGAP 60: Reduciendo el apoyo juvenil a la violencia a través de formación vocacional y transferencias de dinero en Afganistan](https://egap.org/resource/reducing-youth-support-for-violence-through-training-and-cash-transfers-in-afghanistan/)

*Aleatorización por Conglomerado*

  - [Informe de Políticas de EGAP 22: Promoviendo el voto](https://egap.org/resource/brief-22-getting-out-the-vote/)

*Aleatorización por bloques de conglomerados*

  - [Informe de Políticas de EGAP 54: Revelaciones sobre malos manejos de fondos de los gobiernos de turno](https://egap.org/resource/evidence-from-mexico-the-effect-of-incumbent-malfeasance-revelations/)

  - [Informe de Políticas de EGAP 56: Reportando corrupción](https://egap.org/resource/reporting-corruption-in-nigeria-testing-the-effects-of-norms-nudges/)

  
### Herramientas

- [RItools](https://cran.r-project.org/web/packages/RItools/index.html), un conjunto de herramientas para hacer inferencia basada en la aleatorización incluyendo pruebas de equlibrio.
 
