# Poder Estadístico y Diagnosticandos del Diseño {.tabset}


Antes de llevar a cabo un estudio es importante saber si un diseño en particular tiene el poder estadístico necesario para detectar un efecto en dado caso que exista tal efecto. Es difícil aprender de un estudio con poco poder estadístico, ya que no estaría claro si un resultado nulo indica que no hubo efecto o simplemente que no pudimos detectar un efecto que sí existe y es distinto de cero. Un análisis de poder puede ayudar a mejorar un diseño y así poder asignar mejor los recursos; incluso puede ayudar a decidir no realizar el estudio.

En este módulo presentamos: el poder estadístico, los enfoques básicos para calcular el poder mediante cálculos analíticos y mediante la simulación, y cómo las características del diseño como los bloques, el ajuste de covariables y los conglomerados impactan el poder estadístico.

## Contenido Principal

 - **Poder estadístico** es la capacidad que tiene un estudio para detectar un efecto en dado caso que sí exista.
 
 - **El análisis de poder** es algo que se hace antes de realizar un estudio.  Sirve para determinar el tamaño de muestra necesario para detectar un efecto dado o sirve para determinar el tamaño del efecto que se podría detectar dado un tamaño de muestra. El análisis de poder es un paso esencial en el diseño de la investigación y ayuda a que podemos informar a los demás acerca de nuestro diseño.

 - Métodos comunes para calcular el poder estadístico:
 
      - Cálculo **analítico** del poder estadístico  (usando una formula)
 
      - **Simulaciones** (usando, por ejemplo, DeclareDesign)

 - **El ajuste de covariables** y **los bloques** pueden aumentar el poder estadístico.

 - Para el  **diseño por conglomerados** se debe tener en cuenta la correlación entre las unidades que están dentro de cada conglomerado (la varianza interna de los conglomerados con respecto a la varianza total).
 
 - El poder estadístico está muy relacionado con [el diseño de estudios](el-proceso-del-diseño-de-la-investigación.html), [las pruebas de hipótesis ](pruebas-de-hipótesis.html) y la [estimación](estimandos-y-estimadores.html).

## Diapositivas

A continuación presentamos las diapositivas con el contenido principal que cubrimos en nuestra clase sobre poder estadístico.  Usted puede usar directamente los archivos originales de las diapositivas o también puede copiarlos y editarlos localmente.


 - [Archivo de R Markdown](https://egap.github.io/learningdays-resources/Slides/power-slides.Rmd)

 - [Versión en PDF](https://egap.github.io/learningdays-resources/Slides/power-slides.pdf)

 - [Versión de HTML](https://egap.github.io/learningdays-resources/Slides/power-slides.html)

Si desea, también puede ver las diapositivas utilizadas en sesiones pasadas de los Learning Days de EGAP:

 - [Presentación sobre poder estadístico de los  Learning Days de EGAP en La Escuela Africana de Economía, Abomey-Calavi, junio de 2019](https://egap.github.io/learningdays-resources/Slides/Examples/power-benin.pdf)

 - [Presentación sobre poder estadístico de los  Learning Days de EGAP en la Universidad de Los Andes, Bogotá, abril de 2019](https://egap.github.io/learningdays-resources/Slides/Examples/power-bogota.pdf)

 - [Presentación sobre poder estadístico de los  Learning Days de EGAP en la Universidad Católica del Uruguay, Montevideo, marzo 2018](https://egap.github.io/learningdays-resources/Slides/Examples/power-montevideo.pdf)

 - [Presentación sobre poder estadístico de los  Learning Days de EGAP en la Ciudad de Guatemala, Guatemala, agosto de 2017](https://egap.github.io/learningdays-resources/Slides/Examples/power-guatemala.html)

 - [Presentación sobre poder estadístico de los  Learning Days de EGAP en Salima, Malawi, febrero de 2017](https://egap.github.io/learningdays-resources/Slides/Examples/power-malawi.pdf)

 - [Presentación sobre poder estadístico de los  Learning Days de EGAP en la Universidad Diego Portales en Santiago, Chile, mayo de 2016](https://egap.github.io/learningdays-resources/Slides/Examples/power-santiago.pdf)


## Recursos

### Guías de Métodos de EGAP

 - Guía de Métodos de EGAP [10 cosas que usted debe saber sobre poder estadístico](https://egap.org/resource/10-things-you-need-know-about-statistical-power/)

 - Guía de Métodos de EGAP [10 cosas que usted debe saber sobre ajuste de covariables](https://egap.org/resource/10-things-to-know-about-covariate-adjustment/)
 
 - Guía de Métodos de EGAP [10 cosas que resultados sobre lo que los efectos nulos pueden significar](https://egap.org/resource/10-things-your-null-result-might-mean/)

### Notas de políticas de EGAP y PAPs

Algunos ejemplos de análisis de poder en diseños:

 - [Plan de pre-análisis. La rendición de cuentas puede transformar (Accountability Can Transform, ACT) la salud: Una aplicación y extensión de Bjorkman y Svensson (2009)](https://osf.io/qxwmu/)
 
 - [Nota 58 de EGAP sobre políticas: ¿Pueden los sistemas de rendición de cuentas que parten desde abajo mejorar los resultados en materia de salud?](https://egap.org/resource/does-bottom-up-accountability-work-evidence-from-uganda/)


### Herramientas

 - Análisis de poder estadístico interactivo
 
      - [Calculadora de poder estadístico de EGAP](https://egap.shinyapps.io/power-app/)
 
      - [rpsychologist](https://rpsychologist.com/d3/NHST/)

 - Paquetes de R  para análisis de poder estadístico
 
      - [pwr](https://cran.r-project.org/web/packages/pwr/index.html)
 
      - [DeclareDesign](https://cran.r-project.org/web/packages/DeclareDesign/index.html), ver también, <https://declaredesign.org/>

